import { DIFFICULTIES, PERSONAS, TOPICS } from "../constants.ts";
import type { SavedSession } from "../types.ts";

function labelFor(options: ReadonlyArray<{ value: string; label: string }>, value: string): string {
  return options.find((o) => o.value === value)?.label ?? value;
}

function formatReportDate(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });
}

export function buildDebriefReport(session: SavedSession): string {
  const { debrief } = session;
  const lines: string[] = [
    "# Interview Debrief Report",
    "",
    `**Date:** ${formatReportDate(session.date)}`,
    `**Topic:** ${labelFor(TOPICS, session.topic)}`,
    `**Difficulty:** ${labelFor(DIFFICULTIES, session.difficulty)}`,
    `**Interviewer persona:** ${labelFor(PERSONAS, session.persona)}`,
    `**Answers given:** ${session.turnCount}`,
    "",
    `## Readiness Rating: ${debrief.readinessRating}`,
    ""
  ];

  if (debrief.topicsCovered.length > 0) {
    lines.push("## Topics Covered", "", ...debrief.topicsCovered.map((t) => `- ${t}`), "");
  }

  lines.push(
    "## Strengths",
    "",
    debrief.strengths,
    "",
    "## Areas to Improve",
    "",
    debrief.areasToImprove,
    "",
    `> ${debrief.closingNote}`,
    "",
    "## Transcript",
    ""
  );

  for (const message of session.conversation) {
    const speaker = message.role === "user" ? "You" : message.isHint ? "Hint" : "Interviewer";
    lines.push(`**${speaker}:** ${message.content}`, "");
    if (message.code) {
      lines.push("```", message.code, "```", "");
    }
  }

  lines.push("---", "", "_Generated by GenAI Technical Interviewer_");
  return lines.join("\n");
}

export function reportFileName(session: SavedSession): string {
  const date = session.date.slice(0, 10);
  return `interview-debrief-${session.topic}-${date}.md`;
}

export function downloadDebriefReport(session: SavedSession): void {
  const blob = new Blob([buildDebriefReport(session)], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = reportFileName(session);
  anchor.click();
  URL.revokeObjectURL(url);
}
